require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MediaFilesController do

  def mock_media_file(stubs={})
    @mock_media_file ||= mock_model(MediaFile, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all media_files as @media_files" do
      MediaFile.stub(:all) { [mock_media_file] }
      get :index
      assigns(:media_files).should eq([mock_media_file])
    end
  end

  describe "GET show" do
    it "assigns the requested media_file as @media_file" do
      MediaFile.stub(:find).with("37") { mock_media_file }
      get :show, :id => "37"
      assigns(:media_file).should be(mock_media_file)
    end
  end

  describe "GET new" do
    it "assigns a new media_file as @media_file" do
      MediaFile.stub(:new) { mock_media_file }
      get :new
      assigns(:media_file).should be(mock_media_file)
    end
  end

  describe "GET edit" do
    it "assigns the requested media_file as @media_file" do
      MediaFile.stub(:find).with("37") { mock_media_file }
      get :edit, :id => "37"
      assigns(:media_file).should be(mock_media_file)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created media_file as @media_file" do
        MediaFile.stub(:new).with({'these' => 'params'}) { mock_media_file(:save => true) }
        post :create, :media_file => {'these' => 'params'}
        assigns(:media_file).should be(mock_media_file)
      end

      it "redirects to the created media_file" do
        MediaFile.stub(:new) { mock_media_file(:save => true) }
        post :create, :media_file => {}
        response.should redirect_to(media_file_url(mock_media_file))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved media_file as @media_file" do
        MediaFile.stub(:new).with({'these' => 'params'}) { mock_media_file(:save => false) }
        post :create, :media_file => {'these' => 'params'}
        assigns(:media_file).should be(mock_media_file)
      end

      it "re-renders the 'new' template" do
        MediaFile.stub(:new) { mock_media_file(:save => false) }
        post :create, :media_file => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested media_file" do
        MediaFile.stub(:find).with("37") { mock_media_file }
        mock_media_file.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :media_file => {'these' => 'params'}
      end

      it "assigns the requested media_file as @media_file" do
        MediaFile.stub(:find) { mock_media_file(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:media_file).should be(mock_media_file)
      end

      it "redirects to the media_file" do
        MediaFile.stub(:find) { mock_media_file(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(media_file_url(mock_media_file))
      end
    end

    describe "with invalid params" do
      it "assigns the media_file as @media_file" do
        MediaFile.stub(:find) { mock_media_file(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:media_file).should be(mock_media_file)
      end

      it "re-renders the 'edit' template" do
        MediaFile.stub(:find) { mock_media_file(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested media_file" do
      MediaFile.stub(:find).with("37") { mock_media_file }
      mock_media_file.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the media_files list" do
      MediaFile.stub(:find) { mock_media_file }
      delete :destroy, :id => "1"
      response.should redirect_to(media_files_url)
    end
  end

end
