require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe QualityDimensionsController do

  def mock_quality_dimension(stubs={})
    @mock_quality_dimension ||= mock_model(QualityDimension, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all quality_dimensions as @quality_dimensions" do
      QualityDimension.stub(:all) { [mock_quality_dimension] }
      get :index
      assigns(:quality_dimensions).should eq([mock_quality_dimension])
    end
  end

  describe "GET show" do
    it "assigns the requested quality_dimension as @quality_dimension" do
      QualityDimension.stub(:find).with("37") { mock_quality_dimension }
      get :show, :id => "37"
      assigns(:quality_dimension).should be(mock_quality_dimension)
    end
  end

  describe "GET new" do
    it "assigns a new quality_dimension as @quality_dimension" do
      QualityDimension.stub(:new) { mock_quality_dimension }
      get :new
      assigns(:quality_dimension).should be(mock_quality_dimension)
    end
  end

  describe "GET edit" do
    it "assigns the requested quality_dimension as @quality_dimension" do
      QualityDimension.stub(:find).with("37") { mock_quality_dimension }
      get :edit, :id => "37"
      assigns(:quality_dimension).should be(mock_quality_dimension)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created quality_dimension as @quality_dimension" do
        QualityDimension.stub(:new).with({'these' => 'params'}) { mock_quality_dimension(:save => true) }
        post :create, :quality_dimension => {'these' => 'params'}
        assigns(:quality_dimension).should be(mock_quality_dimension)
      end

      it "redirects to the created quality_dimension" do
        QualityDimension.stub(:new) { mock_quality_dimension(:save => true) }
        post :create, :quality_dimension => {}
        response.should redirect_to(quality_dimension_url(mock_quality_dimension))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved quality_dimension as @quality_dimension" do
        QualityDimension.stub(:new).with({'these' => 'params'}) { mock_quality_dimension(:save => false) }
        post :create, :quality_dimension => {'these' => 'params'}
        assigns(:quality_dimension).should be(mock_quality_dimension)
      end

      it "re-renders the 'new' template" do
        QualityDimension.stub(:new) { mock_quality_dimension(:save => false) }
        post :create, :quality_dimension => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested quality_dimension" do
        QualityDimension.stub(:find).with("37") { mock_quality_dimension }
        mock_quality_dimension.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :quality_dimension => {'these' => 'params'}
      end

      it "assigns the requested quality_dimension as @quality_dimension" do
        QualityDimension.stub(:find) { mock_quality_dimension(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:quality_dimension).should be(mock_quality_dimension)
      end

      it "redirects to the quality_dimension" do
        QualityDimension.stub(:find) { mock_quality_dimension(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(quality_dimension_url(mock_quality_dimension))
      end
    end

    describe "with invalid params" do
      it "assigns the quality_dimension as @quality_dimension" do
        QualityDimension.stub(:find) { mock_quality_dimension(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:quality_dimension).should be(mock_quality_dimension)
      end

      it "re-renders the 'edit' template" do
        QualityDimension.stub(:find) { mock_quality_dimension(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested quality_dimension" do
      QualityDimension.stub(:find).with("37") { mock_quality_dimension }
      mock_quality_dimension.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the quality_dimensions list" do
      QualityDimension.stub(:find) { mock_quality_dimension }
      delete :destroy, :id => "1"
      response.should redirect_to(quality_dimensions_url)
    end
  end

end
