require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe QualityMeasuresController do

  def mock_quality_measure(stubs={})
    @mock_quality_measure ||= mock_model(QualityMeasure, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all quality_measures as @quality_measures" do
      QualityMeasure.stub(:all) { [mock_quality_measure] }
      get :index
      assigns(:quality_measures).should eq([mock_quality_measure])
    end
  end

  describe "GET show" do
    it "assigns the requested quality_measure as @quality_measure" do
      QualityMeasure.stub(:find).with("37") { mock_quality_measure }
      get :show, :id => "37"
      assigns(:quality_measure).should be(mock_quality_measure)
    end
  end

  describe "GET new" do
    it "assigns a new quality_measure as @quality_measure" do
      QualityMeasure.stub(:new) { mock_quality_measure }
      get :new
      assigns(:quality_measure).should be(mock_quality_measure)
    end
  end

  describe "GET edit" do
    it "assigns the requested quality_measure as @quality_measure" do
      QualityMeasure.stub(:find).with("37") { mock_quality_measure }
      get :edit, :id => "37"
      assigns(:quality_measure).should be(mock_quality_measure)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created quality_measure as @quality_measure" do
        QualityMeasure.stub(:new).with({'these' => 'params'}) { mock_quality_measure(:save => true) }
        post :create, :quality_measure => {'these' => 'params'}
        assigns(:quality_measure).should be(mock_quality_measure)
      end

      it "redirects to the created quality_measure" do
        QualityMeasure.stub(:new) { mock_quality_measure(:save => true) }
        post :create, :quality_measure => {}
        response.should redirect_to(quality_measure_url(mock_quality_measure))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved quality_measure as @quality_measure" do
        QualityMeasure.stub(:new).with({'these' => 'params'}) { mock_quality_measure(:save => false) }
        post :create, :quality_measure => {'these' => 'params'}
        assigns(:quality_measure).should be(mock_quality_measure)
      end

      it "re-renders the 'new' template" do
        QualityMeasure.stub(:new) { mock_quality_measure(:save => false) }
        post :create, :quality_measure => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested quality_measure" do
        QualityMeasure.stub(:find).with("37") { mock_quality_measure }
        mock_quality_measure.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :quality_measure => {'these' => 'params'}
      end

      it "assigns the requested quality_measure as @quality_measure" do
        QualityMeasure.stub(:find) { mock_quality_measure(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:quality_measure).should be(mock_quality_measure)
      end

      it "redirects to the quality_measure" do
        QualityMeasure.stub(:find) { mock_quality_measure(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(quality_measure_url(mock_quality_measure))
      end
    end

    describe "with invalid params" do
      it "assigns the quality_measure as @quality_measure" do
        QualityMeasure.stub(:find) { mock_quality_measure(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:quality_measure).should be(mock_quality_measure)
      end

      it "re-renders the 'edit' template" do
        QualityMeasure.stub(:find) { mock_quality_measure(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested quality_measure" do
      QualityMeasure.stub(:find).with("37") { mock_quality_measure }
      mock_quality_measure.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the quality_measures list" do
      QualityMeasure.stub(:find) { mock_quality_measure }
      delete :destroy, :id => "1"
      response.should redirect_to(quality_measures_url)
    end
  end

end
